server:
  servlet:
    context-path: '/api'
  port: 7777

logging:
  level:
    com.ssafy: DEBUG

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: #MySQL Database URL
    username: #MySQL username
    password: #MySQL password
  jpa:
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 1000
    show-sql: true
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQL8InnoDBDialect
  redis:
    host: localhost
    port: 6379
  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 200MB
  spring:
    mail:
    host: smtp.gmail.com
    port: 587
    username: 본인의 구글 계정 @gmail.com
    password: 본인의 구글 계정 비밀번호
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true

jwt:
  secret: jwtSecret
  refresh-token-expire: 86400000

cloud:
  aws:
    credentials:
      access-key: ##access-key
      secret-key: ##secret-key
    region:
      static: ap-northeast-2
    s3:
      bucket: ##bucket
    stack:
      auto: false

openvidu:
  url: http://localhost:5443/
  secret: ##MY_SECRET
#openvidu:
#  url: http://localhost:4443/
#  secret: MY_SECRET
